import { College, Review } from "@/types";

export const MOCK_COLLEGES: College[] = [
  {
    id: "1",
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    established: 1958,
    rating: 4.8,
    reviewCount: 1240,
    fees: { min: 200000, max: 250000, average: 225000 },
    placements: {
      averagePackage: 2200000,
      highestPackage: 25000000,
      placementRate: 98,
      topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Amazon"],
    },
    courses: [
      { id: "c1", name: "B.Tech Computer Science", duration: "4 years", fees: 225000, seats: 120, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "c2", name: "M.Tech Data Science", duration: "2 years", fees: 150000, seats: 60, eligibility: "GATE", mode: "Full-time" },
      { id: "c3", name: "MBA", duration: "2 years", fees: 400000, seats: 80, eligibility: "CAT/GMAT", mode: "Full-time" },
    ],
    overview: "IIT Bombay is one of India's premier engineering institutions, known for world-class research, excellent industry connections, and outstanding placement records. Established in 1958, it has consistently ranked among the top engineering institutes in India and Asia.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 3"],
    ranking: { nirf: 3, qs: 149 },
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/1d/Indian_Institute_of_Technology_Bombay_Logo.svg",
    website: "https://www.iitb.ac.in",
    phone: "+91-22-2572-2545",
    email: "info@iitb.ac.in",
    address: "Powai, Mumbai, Maharashtra 400076",
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Cafeteria", "Wi-Fi Campus"],
    tags: ["IIT", "Top Ranked", "Engineering", "Research"],
    isFeatured: true,
  },
  {
    id: "2",
    name: "Indian Institute of Technology Delhi",
    slug: "iit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "Government",
    established: 1961,
    rating: 4.7,
    reviewCount: 980,
    fees: { min: 210000, max: 260000, average: 235000 },
    placements: {
      averagePackage: 2100000,
      highestPackage: 22000000,
      placementRate: 97,
      topRecruiters: ["Apple", "Facebook", "Flipkart", "Deloitte", "BCG"],
    },
    courses: [
      { id: "c4", name: "B.Tech Computer Science", duration: "4 years", fees: 235000, seats: 110, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "c5", name: "B.Tech Electrical", duration: "4 years", fees: 235000, seats: 100, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "c6", name: "M.Tech VLSI", duration: "2 years", fees: 160000, seats: 40, eligibility: "GATE", mode: "Full-time" },
    ],
    overview: "IIT Delhi, located in the heart of India's capital, is a premier technical institution offering undergraduate, postgraduate and doctoral programs in engineering, sciences, technology and management.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 2"],
    ranking: { nirf: 2, qs: 185 },
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/fd/Indian_Institute_of_Technology_Delhi_logo.png",
    website: "https://home.iitd.ac.in",
    phone: "+91-11-2659-7135",
    email: "info@iitd.ac.in",
    address: "Hauz Khas, New Delhi, Delhi 110016",
    facilities: ["Library", "Sports Complex", "Hostel", "Research Labs", "Healthcare", "Cafeteria"],
    tags: ["IIT", "Top Ranked", "Engineering"],
    isFeatured: true,
  },
  {
    id: "3",
    name: "BITS Pilani",
    slug: "bits-pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    type: "Deemed",
    established: 1964,
    rating: 4.5,
    reviewCount: 1560,
    fees: { min: 450000, max: 550000, average: 500000 },
    placements: {
      averagePackage: 1800000,
      highestPackage: 18000000,
      placementRate: 95,
      topRecruiters: ["Oracle", "Qualcomm", "Texas Instruments", "Cisco", "Adobe"],
    },
    courses: [
      { id: "c7", name: "B.E. Computer Science", duration: "4 years", fees: 500000, seats: 160, eligibility: "BITSAT", mode: "Full-time" },
      { id: "c8", name: "B.E. Electronics", duration: "4 years", fees: 500000, seats: 140, eligibility: "BITSAT", mode: "Full-time" },
      { id: "c9", name: "M.Sc Mathematics", duration: "2 years", fees: 380000, seats: 80, eligibility: "BITSAT", mode: "Full-time" },
    ],
    overview: "BITS Pilani is one of India's most prestigious private engineering institutions. Known for its unique dual-degree programs, Practice School program, and strong alumni network in the tech industry.",
    accreditation: ["NAAC A", "NBA"],
    ranking: { nirf: 25 },
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/d/d3/BITS_Pilani-Logo.svg",
    website: "https://www.bits-pilani.ac.in",
    phone: "+91-1596-242210",
    email: "admissions@bits-pilani.ac.in",
    address: "Vidya Vihar Campus, Pilani, Rajasthan 333031",
    facilities: ["Library", "Sports", "Hostel", "Labs", "Healthcare"],
    tags: ["Private", "Deemed", "Engineering", "Dual Degree"],
    isFeatured: true,
  },
  {
    id: "4",
    name: "National Institute of Technology Trichy",
    slug: "nit-trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "Government",
    established: 1964,
    rating: 4.3,
    reviewCount: 870,
    fees: { min: 130000, max: 160000, average: 145000 },
    placements: {
      averagePackage: 1200000,
      highestPackage: 10000000,
      placementRate: 92,
      topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "L&T"],
    },
    courses: [
      { id: "c10", name: "B.Tech Civil", duration: "4 years", fees: 145000, seats: 120, eligibility: "JEE Main", mode: "Full-time" },
      { id: "c11", name: "B.Tech Mechanical", duration: "4 years", fees: 145000, seats: 120, eligibility: "JEE Main", mode: "Full-time" },
      { id: "c12", name: "B.Tech IT", duration: "4 years", fees: 145000, seats: 90, eligibility: "JEE Main", mode: "Full-time" },
    ],
    overview: "NIT Trichy is among India's top National Institutes of Technology, with a strong focus on engineering excellence, research, and industry collaboration. It has consistently produced top-tier engineers.",
    accreditation: ["NAAC A+", "NBA", "NIRF Rank 9"],
    ranking: { nirf: 9 },
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/a/a5/NIT_Trichy_logo.png",
    website: "https://www.nitt.edu",
    phone: "+91-431-2503000",
    email: "info@nitt.edu",
    address: "Tanjore Main Road, Tiruchirappalli, Tamil Nadu 620015",
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare"],
    tags: ["NIT", "Government", "Engineering"],
    isFeatured: false,
  },
  {
    id: "5",
    name: "Vellore Institute of Technology",
    slug: "vit-vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Deemed",
    established: 1984,
    rating: 4.1,
    reviewCount: 2340,
    fees: { min: 350000, max: 450000, average: 400000 },
    placements: {
      averagePackage: 800000,
      highestPackage: 8000000,
      placementRate: 88,
      topRecruiters: ["TCS", "Wipro", "Cognizant", "Accenture", "Capgemini"],
    },
    courses: [
      { id: "c13", name: "B.Tech CSE", duration: "4 years", fees: 400000, seats: 300, eligibility: "VITEEE", mode: "Full-time" },
      { id: "c14", name: "B.Tech ECE", duration: "4 years", fees: 400000, seats: 240, eligibility: "VITEEE", mode: "Full-time" },
      { id: "c15", name: "MBA", duration: "2 years", fees: 600000, seats: 120, eligibility: "CAT/MAT/XAT", mode: "Full-time" },
    ],
    overview: "VIT Vellore is a leading private deemed university known for its world-class infrastructure, innovative curriculum, and excellent placement record with over 400 companies visiting annually.",
    accreditation: ["NAAC A++"],
    ranking: { nirf: 11 },
    image: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/e2/Vellore_Institute_of_Technology_seal_2017.png",
    website: "https://vit.ac.in",
    phone: "+91-416-220-2020",
    email: "ugadmission@vit.ac.in",
    address: "Tiruvalam Road, Vellore, Tamil Nadu 632014",
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Food Court"],
    tags: ["Private", "Deemed", "Engineering", "Large Campus"],
    isFeatured: false,
  },
  {
    id: "6",
    name: "Indian Institute of Management Ahmedabad",
    slug: "iim-ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Government",
    established: 1961,
    rating: 4.9,
    reviewCount: 680,
    fees: { min: 2300000, max: 2500000, average: 2400000 },
    placements: {
      averagePackage: 3500000,
      highestPackage: 80000000,
      placementRate: 100,
      topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "Amazon"],
    },
    courses: [
      { id: "c16", name: "PGP (MBA)", duration: "2 years", fees: 2400000, seats: 400, eligibility: "CAT", mode: "Full-time" },
      { id: "c17", name: "PGPX (1-year MBA)", duration: "1 year", fees: 2800000, seats: 60, eligibility: "GMAT", mode: "Full-time" },
    ],
    overview: "IIMA is India's premier management institution and one of the world's top business schools. Known for its rigorous case-based pedagogy, exceptional alumni network, and unmatched placement record.",
    accreditation: ["NAAC A++", "AACSB", "EQUIS", "AMBA"],
    ranking: { nirf: 1, qs: 45 },
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/e/e8/Indian_Institute_of_Management_Ahmedabad_Logo.svg",
    website: "https://www.iima.ac.in",
    phone: "+91-79-6632-4444",
    email: "pgpoffice@iima.ac.in",
    address: "Vastrapur, Ahmedabad, Gujarat 380015",
    facilities: ["Library", "Sports", "Hostel", "Case Study Rooms", "Healthcare"],
    tags: ["IIM", "MBA", "Top Management", "Government"],
    isFeatured: true,
  },
  {
    id: "7",
    name: "Delhi Technological University",
    slug: "dtu-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "Government",
    established: 1941,
    rating: 4.0,
    reviewCount: 1120,
    fees: { min: 80000, max: 120000, average: 100000 },
    placements: {
      averagePackage: 1000000,
      highestPackage: 7000000,
      placementRate: 85,
      topRecruiters: ["Amazon", "Microsoft", "Samsung", "Paytm", "Zomato"],
    },
    courses: [
      { id: "c18", name: "B.Tech Software", duration: "4 years", fees: 100000, seats: 180, eligibility: "JEE Main", mode: "Full-time" },
      { id: "c19", name: "B.Tech Mechanical", duration: "4 years", fees: 100000, seats: 180, eligibility: "JEE Main", mode: "Full-time" },
      { id: "c20", name: "M.Tech CSE", duration: "2 years", fees: 120000, seats: 40, eligibility: "GATE", mode: "Full-time" },
    ],
    overview: "DTU, formerly Delhi College of Engineering, is one of India's oldest and most reputed technical institutions. Located in Delhi, it offers excellent engineering programs with strong industry ties in the NCR region.",
    accreditation: ["NAAC A", "NBA"],
    ranking: { nirf: 36 },
    image: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/b/b5/Delhi_Technological_University_logo.png",
    website: "http://www.dtu.ac.in",
    phone: "+91-11-2787-1018",
    email: "info@dtu.ac.in",
    address: "Bawana Road, Delhi, Delhi 110042",
    facilities: ["Library", "Sports Ground", "Hostel", "Labs"],
    tags: ["State University", "Engineering", "Delhi"],
    isFeatured: false,
  },
  {
    id: "8",
    name: "Manipal Institute of Technology",
    slug: "manipal-mit",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    type: "Private",
    established: 1957,
    rating: 4.2,
    reviewCount: 1890,
    fees: { min: 400000, max: 500000, average: 450000 },
    placements: {
      averagePackage: 750000,
      highestPackage: 6000000,
      placementRate: 86,
      topRecruiters: ["Infosys", "TCS", "Wipro", "Accenture", "IBM"],
    },
    courses: [
      { id: "c21", name: "B.Tech CSE", duration: "4 years", fees: 450000, seats: 240, eligibility: "MET/JEE", mode: "Full-time" },
      { id: "c22", name: "B.Tech Biomedical", duration: "4 years", fees: 450000, seats: 60, eligibility: "MET/JEE", mode: "Full-time" },
      { id: "c23", name: "B.Arch", duration: "5 years", fees: 500000, seats: 40, eligibility: "NATA", mode: "Full-time" },
    ],
    overview: "MIT Manipal is a renowned private engineering college within Manipal Academy of Higher Education. Known for its vibrant campus life, strong alumni network, and diverse academic programs.",
    accreditation: ["NAAC A+", "NBA"],
    ranking: { nirf: 52 },
    image: "https://images.unsplash.com/photo-1567168544813-cc03465b4fa8?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/a/a0/Manipal_Institute_of_Technology_logo.png",
    website: "https://manipal.edu/mit.html",
    phone: "+91-820-292-5000",
    email: "admissions@manipal.edu",
    address: "Udupi District, Manipal, Karnataka 576104",
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Beach"],
    tags: ["Private", "Engineering", "Coastal Campus"],
    isFeatured: false,
  },
  {
    id: "9",
    name: "Jadavpur University",
    slug: "jadavpur-university",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    type: "Government",
    established: 1955,
    rating: 4.2,
    reviewCount: 760,
    fees: { min: 15000, max: 30000, average: 22000 },
    placements: {
      averagePackage: 900000,
      highestPackage: 6500000,
      placementRate: 80,
      topRecruiters: ["TCS", "Infosys", "HCL", "IBM", "Cognizant"],
    },
    courses: [
      { id: "c24", name: "B.E. CSE", duration: "4 years", fees: 22000, seats: 120, eligibility: "WBJEE", mode: "Full-time" },
      { id: "c25", name: "B.E. Chemical", duration: "4 years", fees: 22000, seats: 90, eligibility: "WBJEE", mode: "Full-time" },
    ],
    overview: "Jadavpur University is one of the most prestigious government universities in India, known for its quality education at minimal fees. Strong in engineering and sciences, with excellent academic reputation.",
    accreditation: ["NAAC A++"],
    ranking: { nirf: 12 },
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/79/Jadavpur_University_logo.png",
    website: "http://www.jaduniv.edu.in",
    phone: "+91-33-2414-6666",
    email: "registrar@jadavpur.edu.in",
    address: "188, Raja S C Mallick Rd, Kolkata, West Bengal 700032",
    facilities: ["Library", "Sports Ground", "Hostel", "Labs"],
    tags: ["State University", "Affordable", "Engineering"],
    isFeatured: false,
  },
  {
    id: "10",
    name: "SRM Institute of Science and Technology",
    slug: "srm-kattankulathur",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Deemed",
    established: 1985,
    rating: 3.9,
    reviewCount: 2100,
    fees: { min: 300000, max: 400000, average: 350000 },
    placements: {
      averagePackage: 650000,
      highestPackage: 5000000,
      placementRate: 82,
      topRecruiters: ["TCS", "Wipro", "Infosys", "HCL", "CTS"],
    },
    courses: [
      { id: "c26", name: "B.Tech CSE", duration: "4 years", fees: 350000, seats: 400, eligibility: "SRMJEE", mode: "Full-time" },
      { id: "c27", name: "B.Tech Mechatronics", duration: "4 years", fees: 350000, seats: 60, eligibility: "SRMJEE", mode: "Full-time" },
    ],
    overview: "SRM Institute is a large private deemed university with one of the biggest engineering programs in India. Known for massive intake, good infrastructure, and active industry collaborations.",
    accreditation: ["NAAC A++"],
    ranking: { nirf: 30 },
    image: "https://images.unsplash.com/photo-1572979270937-2ed5e83b6f5f?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/f/f4/SRM_University_logo.png",
    website: "https://www.srmist.edu.in",
    phone: "+91-44-2745-5510",
    email: "admissions@srmist.edu.in",
    address: "Kattankulathur, Chennai, Tamil Nadu 603203",
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Food Court"],
    tags: ["Private", "Large Campus", "Engineering"],
    isFeatured: false,
  },
  {
    id: "11",
    name: "Amity University Noida",
    slug: "amity-noida",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    type: "Private",
    established: 2005,
    rating: 3.7,
    reviewCount: 1650,
    fees: { min: 280000, max: 380000, average: 330000 },
    placements: {
      averagePackage: 550000,
      highestPackage: 4000000,
      placementRate: 75,
      topRecruiters: ["Deloitte", "EY", "KPMG", "Wipro", "HCL"],
    },
    courses: [
      { id: "c28", name: "B.Tech CSE", duration: "4 years", fees: 330000, seats: 200, eligibility: "Amity JEE", mode: "Full-time" },
      { id: "c29", name: "BBA", duration: "3 years", fees: 280000, seats: 120, eligibility: "Merit", mode: "Full-time" },
      { id: "c30", name: "MBA", duration: "2 years", fees: 500000, seats: 120, eligibility: "CAT/MAT", mode: "Full-time" },
    ],
    overview: "Amity University is a large private university offering diverse programs across engineering, management, law, and more. Known for its modern campus and corporate-focused curriculum.",
    accreditation: ["NAAC A"],
    ranking: { nirf: 58 },
    image: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/71/Amity_University_logo.jpg",
    website: "https://www.amity.edu",
    phone: "+91-120-4392-000",
    email: "admissions@amity.edu",
    address: "Sector 125, Noida, Uttar Pradesh 201313",
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Mall"],
    tags: ["Private", "Multi-Disciplinary", "Large Campus"],
    isFeatured: false,
  },
  {
    id: "12",
    name: "Indian Institute of Technology Madras",
    slug: "iit-madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    established: 1959,
    rating: 4.9,
    reviewCount: 1100,
    fees: { min: 205000, max: 255000, average: 230000 },
    placements: {
      averagePackage: 2300000,
      highestPackage: 26000000,
      placementRate: 99,
      topRecruiters: ["Google", "Apple", "Microsoft", "Samsung", "Amazon"],
    },
    courses: [
      { id: "c31", name: "B.Tech Aerospace", duration: "4 years", fees: 230000, seats: 50, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "c32", name: "B.Tech CSE", duration: "4 years", fees: 230000, seats: 115, eligibility: "JEE Advanced", mode: "Full-time" },
      { id: "c33", name: "M.S. Research", duration: "2 years", fees: 150000, seats: 200, eligibility: "GATE", mode: "Full-time" },
    ],
    overview: "IIT Madras, India's #1 ranked institution (NIRF 2023), is located in a beautiful forested campus in Chennai. Known for cutting-edge research, startup ecosystem, and exceptional alumni.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 1"],
    ranking: { nirf: 1, qs: 227 },
    image: "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=800",
    logo: "https://upload.wikimedia.org/wikipedia/en/6/69/IIT_Madras_Logo.svg",
    website: "https://www.iitm.ac.in",
    phone: "+91-44-2257-8280",
    email: "registrar@iitm.ac.in",
    address: "IIT PO, Chennai, Tamil Nadu 600036",
    facilities: ["Library", "Sports Complex", "Hostel", "Research Parks", "Healthcare", "Deer Park"],
    tags: ["IIT", "NIRF #1", "Engineering", "Research", "Startup Hub"],
    isFeatured: true,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    collegeId: "1",
    userId: "u1",
    userName: "Rahul Sharma",
    rating: 5,
    title: "Best Engineering College in India",
    content: "My 4 years at IIT Bombay were transformational. The quality of professors, research opportunities, and peer learning is unmatched.",
    pros: "World-class faculty, excellent research facilities, great peer network, amazing placement opportunities",
    cons: "Very competitive environment, high academic pressure, expensive on-campus food",
    batch: "2023",
    course: "B.Tech Computer Science",
    createdAt: "2024-05-15T10:00:00Z",
    helpful: 142,
  },
  {
    id: "r2",
    collegeId: "1",
    userId: "u2",
    userName: "Priya Patel",
    rating: 4,
    title: "Excellent but intense",
    content: "Great college with top resources, but the workload is immense. Make sure you're ready for the challenge.",
    pros: "Excellent placement, top faculty, great alumni network",
    cons: "Very high academic pressure, limited social life initially",
    batch: "2022",
    course: "B.Tech Electrical Engineering",
    createdAt: "2024-03-10T10:00:00Z",
    helpful: 89,
  },
  {
    id: "r3",
    collegeId: "2",
    userId: "u3",
    userName: "Amit Kumar",
    rating: 5,
    title: "Phenomenal experience",
    content: "IIT Delhi offers an incredible blend of academics, research, and industry exposure. Being in Delhi gives added advantages.",
    pros: "Delhi location, excellent industry exposure, top placements, world-class labs",
    cons: "Delhi weather, intense competition",
    batch: "2023",
    course: "B.Tech Computer Science",
    createdAt: "2024-04-20T10:00:00Z",
    helpful: 98,
  },
  {
    id: "r4",
    collegeId: "3",
    userId: "u4",
    userName: "Sneha Gupta",
    rating: 4,
    title: "Great private engineering college",
    content: "BITS Pilani's dual degree and practice school programs are unique advantages. Strong alumni network in the tech industry.",
    pros: "Unique curriculum, great industry connections, liberal campus culture",
    cons: "High fees, remote location, competitive entrance",
    batch: "2023",
    course: "B.E. Computer Science",
    createdAt: "2024-02-14T10:00:00Z",
    helpful: 76,
  },
];

export const INDIAN_STATES = [
  "All States",
  "Andhra Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh",
  "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh",
  "Jammu & Kashmir", "Jharkhand", "Karnataka", "Kerala",
  "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya",
  "Odisha", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana",
  "Uttar Pradesh", "Uttarakhand", "West Bengal"
];
