process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: true });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const colleges = [
  {
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    type: "GOVERNMENT" as const,
    established: 1958,
    rating: 4.8,
    reviewCount: 1240,
    feesMin: 200000, feesMax: 250000, feesAverage: 225000,
    avgPackage: 2200000, highestPkg: 25000000, placementRate: 98,
    topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey", "Amazon"],
    overview: "IIT Bombay is one of India's premier engineering institutions, known for world-class research, excellent industry connections, and outstanding placement records. Established in 1958, it has consistently ranked among the top engineering institutes in India and Asia.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 3"],
    nirfRank: 3, qsRank: 149,
    image: "https://images.unsplash.com/photo-1562774053-701939374585?w=800",
    isFeatured: true,
    tags: ["IIT", "Top Ranked", "Engineering", "Research"],
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Cafeteria", "Wi-Fi Campus"],
    website: "https://www.iitb.ac.in", phone: "+91-22-2572-2545",
    email: "info@iitb.ac.in", address: "Powai, Mumbai, Maharashtra 400076",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 225000, seats: 120, eligibility: "JEE Advanced", mode: "FULL_TIME" as const },
      { name: "M.Tech Data Science", duration: "2 years", fees: 150000, seats: 60, eligibility: "GATE", mode: "FULL_TIME" as const },
      { name: "MBA", duration: "2 years", fees: 400000, seats: 80, eligibility: "CAT/GMAT", mode: "FULL_TIME" as const },
    ],
    reviews: [
      { rating: 5, title: "Best Engineering College in India", content: "My 4 years at IIT Bombay were transformational. The quality of professors, research opportunities, and peer learning is unmatched.", pros: "World-class faculty, excellent research facilities, great peer network", cons: "Very competitive environment, high academic pressure", batch: "2023", course: "B.Tech Computer Science", helpful: 142 },
      { rating: 4, title: "Excellent but intense", content: "Great college with top resources, but the workload is immense. Make sure you're ready for the challenge.", pros: "Excellent placement, top faculty, great alumni network", cons: "Very high academic pressure, limited social life initially", batch: "2022", course: "B.Tech Electrical Engineering", helpful: 89 },
    ],
  },
  {
    name: "Indian Institute of Technology Delhi",
    slug: "iit-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT" as const,
    established: 1961,
    rating: 4.7,
    reviewCount: 980,
    feesMin: 210000, feesMax: 260000, feesAverage: 235000,
    avgPackage: 2100000, highestPkg: 22000000, placementRate: 97,
    topRecruiters: ["Apple", "Facebook", "Flipkart", "Deloitte", "BCG"],
    overview: "IIT Delhi, located in the heart of India's capital, is a premier technical institution offering undergraduate, postgraduate and doctoral programs in engineering, sciences, technology and management.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 2"],
    nirfRank: 2, qsRank: 185,
    image: "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800",
    isFeatured: true,
    tags: ["IIT", "Top Ranked", "Engineering"],
    facilities: ["Library", "Sports Complex", "Hostel", "Research Labs", "Healthcare", "Cafeteria"],
    website: "https://home.iitd.ac.in", phone: "+91-11-2659-7135",
    email: "info@iitd.ac.in", address: "Hauz Khas, New Delhi, Delhi 110016",
    courses: [
      { name: "B.Tech Computer Science", duration: "4 years", fees: 235000, seats: 110, eligibility: "JEE Advanced", mode: "FULL_TIME" as const },
      { name: "B.Tech Electrical", duration: "4 years", fees: 235000, seats: 100, eligibility: "JEE Advanced", mode: "FULL_TIME" as const },
      { name: "M.Tech VLSI", duration: "2 years", fees: 160000, seats: 40, eligibility: "GATE", mode: "FULL_TIME" as const },
    ],
    reviews: [
      { rating: 5, title: "Phenomenal experience", content: "IIT Delhi offers an incredible blend of academics, research, and industry exposure. Being in Delhi gives added advantages.", pros: "Delhi location, excellent industry exposure, top placements, world-class labs", cons: "Delhi weather, intense competition", batch: "2023", course: "B.Tech Computer Science", helpful: 98 },
    ],
  },
  {
    name: "BITS Pilani",
    slug: "bits-pilani",
    location: "Pilani, Rajasthan",
    city: "Pilani",
    state: "Rajasthan",
    type: "DEEMED" as const,
    established: 1964,
    rating: 4.5,
    reviewCount: 1560,
    feesMin: 450000, feesMax: 550000, feesAverage: 500000,
    avgPackage: 1800000, highestPkg: 18000000, placementRate: 95,
    topRecruiters: ["Oracle", "Qualcomm", "Texas Instruments", "Cisco", "Adobe"],
    overview: "BITS Pilani is one of India's most prestigious private engineering institutions. Known for its unique dual-degree programs, Practice School program, and strong alumni network in the tech industry.",
    accreditation: ["NAAC A", "NBA"],
    nirfRank: 25, qsRank: null,
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800",
    isFeatured: true,
    tags: ["Private", "Deemed", "Engineering", "Dual Degree"],
    facilities: ["Library", "Sports", "Hostel", "Labs", "Healthcare"],
    website: "https://www.bits-pilani.ac.in", phone: "+91-1596-242210",
    email: "admissions@bits-pilani.ac.in", address: "Vidya Vihar Campus, Pilani, Rajasthan 333031",
    courses: [
      { name: "B.E. Computer Science", duration: "4 years", fees: 500000, seats: 160, eligibility: "BITSAT", mode: "FULL_TIME" as const },
      { name: "B.E. Electronics", duration: "4 years", fees: 500000, seats: 140, eligibility: "BITSAT", mode: "FULL_TIME" as const },
      { name: "M.Sc Mathematics", duration: "2 years", fees: 380000, seats: 80, eligibility: "BITSAT", mode: "FULL_TIME" as const },
    ],
    reviews: [
      { rating: 4, title: "Great private engineering college", content: "BITS Pilani's dual degree and practice school programs are unique advantages. Strong alumni network in the tech industry.", pros: "Unique curriculum, great industry connections, liberal campus culture", cons: "High fees, remote location, competitive entrance", batch: "2023", course: "B.E. Computer Science", helpful: 76 },
    ],
  },
  {
    name: "National Institute of Technology Trichy",
    slug: "nit-trichy",
    location: "Tiruchirappalli, Tamil Nadu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "GOVERNMENT" as const,
    established: 1964,
    rating: 4.3,
    reviewCount: 870,
    feesMin: 130000, feesMax: 160000, feesAverage: 145000,
    avgPackage: 1200000, highestPkg: 10000000, placementRate: 92,
    topRecruiters: ["TCS", "Infosys", "Wipro", "HCL", "L&T"],
    overview: "NIT Trichy is among India's top National Institutes of Technology, with a strong focus on engineering excellence, research, and industry collaboration.",
    accreditation: ["NAAC A+", "NBA", "NIRF Rank 9"],
    nirfRank: 9, qsRank: null,
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800",
    isFeatured: false,
    tags: ["NIT", "Government", "Engineering"],
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare"],
    website: "https://www.nitt.edu", phone: "+91-431-2503000",
    email: "info@nitt.edu", address: "Tanjore Main Road, Tiruchirappalli, Tamil Nadu 620015",
    courses: [
      { name: "B.Tech Civil", duration: "4 years", fees: 145000, seats: 120, eligibility: "JEE Main", mode: "FULL_TIME" as const },
      { name: "B.Tech Mechanical", duration: "4 years", fees: 145000, seats: 120, eligibility: "JEE Main", mode: "FULL_TIME" as const },
      { name: "B.Tech IT", duration: "4 years", fees: 145000, seats: 90, eligibility: "JEE Main", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Vellore Institute of Technology",
    slug: "vit-vellore",
    location: "Vellore, Tamil Nadu",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "DEEMED" as const,
    established: 1984,
    rating: 4.1,
    reviewCount: 2340,
    feesMin: 350000, feesMax: 450000, feesAverage: 400000,
    avgPackage: 800000, highestPkg: 8000000, placementRate: 88,
    topRecruiters: ["TCS", "Wipro", "Cognizant", "Accenture", "Capgemini"],
    overview: "VIT Vellore is a leading private deemed university known for its world-class infrastructure, innovative curriculum, and excellent placement record with over 400 companies visiting annually.",
    accreditation: ["NAAC A++"],
    nirfRank: 11, qsRank: null,
    image: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800",
    isFeatured: false,
    tags: ["Private", "Deemed", "Engineering", "Large Campus"],
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Food Court"],
    website: "https://vit.ac.in", phone: "+91-416-220-2020",
    email: "ugadmission@vit.ac.in", address: "Tiruvalam Road, Vellore, Tamil Nadu 632014",
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 400000, seats: 300, eligibility: "VITEEE", mode: "FULL_TIME" as const },
      { name: "B.Tech ECE", duration: "4 years", fees: 400000, seats: 240, eligibility: "VITEEE", mode: "FULL_TIME" as const },
      { name: "MBA", duration: "2 years", fees: 600000, seats: 120, eligibility: "CAT/MAT/XAT", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Indian Institute of Management Ahmedabad",
    slug: "iim-ahmedabad",
    location: "Ahmedabad, Gujarat",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "GOVERNMENT" as const,
    established: 1961,
    rating: 4.9,
    reviewCount: 680,
    feesMin: 2300000, feesMax: 2500000, feesAverage: 2400000,
    avgPackage: 3500000, highestPkg: 80000000, placementRate: 100,
    topRecruiters: ["McKinsey", "BCG", "Bain", "Goldman Sachs", "Amazon"],
    overview: "IIMA is India's premier management institution and one of the world's top business schools. Known for its rigorous case-based pedagogy, exceptional alumni network, and unmatched placement record.",
    accreditation: ["NAAC A++", "AACSB", "EQUIS", "AMBA"],
    nirfRank: 1, qsRank: 45,
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    isFeatured: true,
    tags: ["IIM", "MBA", "Top Management", "Government"],
    facilities: ["Library", "Sports", "Hostel", "Case Study Rooms", "Healthcare"],
    website: "https://www.iima.ac.in", phone: "+91-79-6632-4444",
    email: "pgpoffice@iima.ac.in", address: "Vastrapur, Ahmedabad, Gujarat 380015",
    courses: [
      { name: "PGP (MBA)", duration: "2 years", fees: 2400000, seats: 400, eligibility: "CAT", mode: "FULL_TIME" as const },
      { name: "PGPX (1-year MBA)", duration: "1 year", fees: 2800000, seats: 60, eligibility: "GMAT", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Delhi Technological University",
    slug: "dtu-delhi",
    location: "New Delhi, Delhi",
    city: "New Delhi",
    state: "Delhi",
    type: "GOVERNMENT" as const,
    established: 1941,
    rating: 4.0,
    reviewCount: 1120,
    feesMin: 80000, feesMax: 120000, feesAverage: 100000,
    avgPackage: 1000000, highestPkg: 7000000, placementRate: 85,
    topRecruiters: ["Amazon", "Microsoft", "Samsung", "Paytm", "Zomato"],
    overview: "DTU, formerly Delhi College of Engineering, is one of India's oldest and most reputed technical institutions. Located in Delhi, it offers excellent engineering programs with strong industry ties in the NCR region.",
    accreditation: ["NAAC A", "NBA"],
    nirfRank: 36, qsRank: null,
    image: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=800",
    isFeatured: false,
    tags: ["State University", "Engineering", "Delhi"],
    facilities: ["Library", "Sports Ground", "Hostel", "Labs"],
    website: "http://www.dtu.ac.in", phone: "+91-11-2787-1018",
    email: "info@dtu.ac.in", address: "Bawana Road, Delhi, Delhi 110042",
    courses: [
      { name: "B.Tech Software", duration: "4 years", fees: 100000, seats: 180, eligibility: "JEE Main", mode: "FULL_TIME" as const },
      { name: "B.Tech Mechanical", duration: "4 years", fees: 100000, seats: 180, eligibility: "JEE Main", mode: "FULL_TIME" as const },
      { name: "M.Tech CSE", duration: "2 years", fees: 120000, seats: 40, eligibility: "GATE", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Manipal Institute of Technology",
    slug: "manipal-mit",
    location: "Manipal, Karnataka",
    city: "Manipal",
    state: "Karnataka",
    type: "PRIVATE" as const,
    established: 1957,
    rating: 4.2,
    reviewCount: 1890,
    feesMin: 400000, feesMax: 500000, feesAverage: 450000,
    avgPackage: 750000, highestPkg: 6000000, placementRate: 86,
    topRecruiters: ["Infosys", "TCS", "Wipro", "Accenture", "IBM"],
    overview: "MIT Manipal is a renowned private engineering college within Manipal Academy of Higher Education. Known for its vibrant campus life, strong alumni network, and diverse academic programs.",
    accreditation: ["NAAC A+", "NBA"],
    nirfRank: 52, qsRank: null,
    image: "https://images.unsplash.com/photo-1567168544813-cc03465b4fa8?w=800",
    isFeatured: false,
    tags: ["Private", "Engineering", "Coastal Campus"],
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Beach"],
    website: "https://manipal.edu/mit.html", phone: "+91-820-292-5000",
    email: "admissions@manipal.edu", address: "Udupi District, Manipal, Karnataka 576104",
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 450000, seats: 240, eligibility: "MET/JEE", mode: "FULL_TIME" as const },
      { name: "B.Tech Biomedical", duration: "4 years", fees: 450000, seats: 60, eligibility: "MET/JEE", mode: "FULL_TIME" as const },
      { name: "B.Arch", duration: "5 years", fees: 500000, seats: 40, eligibility: "NATA", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Jadavpur University",
    slug: "jadavpur-university",
    location: "Kolkata, West Bengal",
    city: "Kolkata",
    state: "West Bengal",
    type: "GOVERNMENT" as const,
    established: 1955,
    rating: 4.2,
    reviewCount: 760,
    feesMin: 15000, feesMax: 30000, feesAverage: 22000,
    avgPackage: 900000, highestPkg: 6500000, placementRate: 80,
    topRecruiters: ["TCS", "Infosys", "HCL", "IBM", "Cognizant"],
    overview: "Jadavpur University is one of the most prestigious government universities in India, known for its quality education at minimal fees. Strong in engineering and sciences.",
    accreditation: ["NAAC A++"],
    nirfRank: 12, qsRank: null,
    image: "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800",
    isFeatured: false,
    tags: ["State University", "Affordable", "Engineering"],
    facilities: ["Library", "Sports Ground", "Hostel", "Labs"],
    website: "http://www.jaduniv.edu.in", phone: "+91-33-2414-6666",
    email: "registrar@jadavpur.edu.in", address: "188, Raja S C Mallick Rd, Kolkata, West Bengal 700032",
    courses: [
      { name: "B.E. CSE", duration: "4 years", fees: 22000, seats: 120, eligibility: "WBJEE", mode: "FULL_TIME" as const },
      { name: "B.E. Chemical", duration: "4 years", fees: 22000, seats: 90, eligibility: "WBJEE", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "SRM Institute of Science and Technology",
    slug: "srm-kattankulathur",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "DEEMED" as const,
    established: 1985,
    rating: 3.9,
    reviewCount: 2100,
    feesMin: 300000, feesMax: 400000, feesAverage: 350000,
    avgPackage: 650000, highestPkg: 5000000, placementRate: 82,
    topRecruiters: ["TCS", "Wipro", "Infosys", "HCL", "CTS"],
    overview: "SRM Institute is a large private deemed university with one of the biggest engineering programs in India. Known for massive intake, good infrastructure, and active industry collaborations.",
    accreditation: ["NAAC A++"],
    nirfRank: 30, qsRank: null,
    image: "https://images.unsplash.com/photo-1572979270937-2ed5e83b6f5f?w=800",
    isFeatured: false,
    tags: ["Private", "Large Campus", "Engineering"],
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Food Court"],
    website: "https://www.srmist.edu.in", phone: "+91-44-2745-5510",
    email: "admissions@srmist.edu.in", address: "Kattankulathur, Chennai, Tamil Nadu 603203",
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 350000, seats: 400, eligibility: "SRMJEE", mode: "FULL_TIME" as const },
      { name: "B.Tech Mechatronics", duration: "4 years", fees: 350000, seats: 60, eligibility: "SRMJEE", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Amity University Noida",
    slug: "amity-noida",
    location: "Noida, Uttar Pradesh",
    city: "Noida",
    state: "Uttar Pradesh",
    type: "PRIVATE" as const,
    established: 2005,
    rating: 3.7,
    reviewCount: 1650,
    feesMin: 280000, feesMax: 380000, feesAverage: 330000,
    avgPackage: 550000, highestPkg: 4000000, placementRate: 75,
    topRecruiters: ["Deloitte", "EY", "KPMG", "Wipro", "HCL"],
    overview: "Amity University is a large private university offering diverse programs across engineering, management, law, and more. Known for its modern campus and corporate-focused curriculum.",
    accreditation: ["NAAC A"],
    nirfRank: 58, qsRank: null,
    image: "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800",
    isFeatured: false,
    tags: ["Private", "Multi-Disciplinary", "Large Campus"],
    facilities: ["Library", "Sports Complex", "Hostel", "Labs", "Healthcare", "Mall"],
    website: "https://www.amity.edu", phone: "+91-120-4392-000",
    email: "admissions@amity.edu", address: "Sector 125, Noida, Uttar Pradesh 201313",
    courses: [
      { name: "B.Tech CSE", duration: "4 years", fees: 330000, seats: 200, eligibility: "Amity JEE", mode: "FULL_TIME" as const },
      { name: "BBA", duration: "3 years", fees: 280000, seats: 120, eligibility: "Merit", mode: "FULL_TIME" as const },
      { name: "MBA", duration: "2 years", fees: 500000, seats: 120, eligibility: "CAT/MAT", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
  {
    name: "Indian Institute of Technology Madras",
    slug: "iit-madras",
    location: "Chennai, Tamil Nadu",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "GOVERNMENT" as const,
    established: 1959,
    rating: 4.9,
    reviewCount: 1100,
    feesMin: 205000, feesMax: 255000, feesAverage: 230000,
    avgPackage: 2300000, highestPkg: 26000000, placementRate: 99,
    topRecruiters: ["Google", "Apple", "Microsoft", "Samsung", "Amazon"],
    overview: "IIT Madras, India's #1 ranked institution (NIRF 2023), is located in a beautiful forested campus in Chennai. Known for cutting-edge research, startup ecosystem, and exceptional alumni.",
    accreditation: ["NAAC A++", "NBA", "NIRF Rank 1"],
    nirfRank: 1, qsRank: 227,
    image: "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=800",
    isFeatured: true,
    tags: ["IIT", "NIRF #1", "Engineering", "Research", "Startup Hub"],
    facilities: ["Library", "Sports Complex", "Hostel", "Research Parks", "Healthcare", "Deer Park"],
    website: "https://www.iitm.ac.in", phone: "+91-44-2257-8280",
    email: "registrar@iitm.ac.in", address: "IIT PO, Chennai, Tamil Nadu 600036",
    courses: [
      { name: "B.Tech Aerospace", duration: "4 years", fees: 230000, seats: 50, eligibility: "JEE Advanced", mode: "FULL_TIME" as const },
      { name: "B.Tech CSE", duration: "4 years", fees: 230000, seats: 115, eligibility: "JEE Advanced", mode: "FULL_TIME" as const },
      { name: "M.S. Research", duration: "2 years", fees: 150000, seats: 200, eligibility: "GATE", mode: "FULL_TIME" as const },
    ],
    reviews: [],
  },
];

async function main() {
  console.log("🌱 Seeding database with all 12 colleges...\n");

  for (const { courses, reviews, ...college } of colleges) {
    const created = await prisma.college.upsert({
      where: { slug: college.slug },
      update: {},
      create: {
        ...college,
        courses: { create: courses },
      },
    });

    // Seed reviews for colleges that have them
    for (const review of reviews) {
      // Create a system user for seeded reviews if needed
      const systemUser = await prisma.collegeUser.upsert({
        where: { email: "seed@collegequest.in" },
        update: {},
        create: {
          name: "CollegeQuest Team",
          email: "seed@collegequest.in",
          password: "n/a",
        },
      });

      await prisma.review.create({
        data: {
          ...review,
          collegeId: created.id,
          userId: systemUser.id,
        },
      });
    }

    const reviewCount = reviews.length;
    console.log(`✅ ${created.name} (${courses.length} courses, ${reviewCount} reviews)`);
  }

  console.log("\n🎉 All 12 colleges seeded successfully!");
}

main()
  .catch((e) => { console.error("❌ Seed failed:", e); process.exit(1); })
  .finally(() => prisma.$disconnect());
